## genotyping log 

# table with rfid, project_name, date, qc pass, lcation on tscc 
# generated by Deng/Riyan with details about sample redos, QC failed samples, location of important files on TSCC

setwd("~/Dropbox (Palmer Lab)/Palmer Lab/Bonnie Lin/github/PalmerLab_genotyping/CREATE")
# from 07/23/2020
HS_n672_orig <- read.table("HS_n672_samplenames.txt") 
# fix dupe ids and reassign the subject id to the vcf 
HS_n672_orig %>% 
  separate(V1, c("sample_id", "rfid"), "-") %>% 
  mutate(rfid = replace(rfid, sample_id == "120138361", "933000120138561")) %>% 
  select(rfid)
  write(file = "HS_n672_samplenames_fix.txt")
