## SAMPLE BARCODE LIBRARY 
# TABLE GENERATED BY KHAI/HANNAH 
# INFO IN THIS TABLE IS USED FOR DEMULTIPLEXING 

# columns should include RFID, project_name, barcode, library, and notes 


################################# 
## SAMPLE BARCODE LIBRARY TABLE 
################################# 

# get rid of the Riptide filter to see the UMich data
setwd("~/Dropbox (Palmer Lab)/Palmer Lab/Bonnie Lin/U01/20190829_WFU_U01_ShippingMaster/Tissues/Original")
flowcell_files <- list.files(path = ".", pattern = "^\\d{4}-\\d{2}-\\d{2}-Flowcell Sample-Barcode list.*[^)].xlsx")

u01.importxlsx <- function(xlname){
  path_sheetnames <- readxl::excel_sheets(xlname)
  df <- lapply(readxl::excel_sheets(path = xlname), readxl::read_excel, path = xlname)
  names(df) <- path_sheetnames
  return(df)
} 

flowcell <- lapply(flowcell_files, function(x){
  x <- u01.importxlsx(x)[[1]] %>% 
    clean_names() 
  return(x)
})
names(flowcell) <- flowcell_files 

flowcell_df <- flowcell %>% rbindlist(idcol = "filename", fill = T, use.names = T) %>% 
  mutate(comment = coalesce(comments_8, comments_9)) %>% 
  select(-c("x7", "comments_8", "comments_9", "flow_cell_lane")) %>%  # columns that only contain NA or have been coalesced
  # dplyr::filter(grepl("Riptide", library)) %>% 
  mutate(comment = toupper(comment)) %>% 
  mutate(rfid = ifelse(grepl("^\\d{9}$", sample_id),
                       paste0("933000", sample_id), sample_id_demul))  # create a column for rfid if it doesn't already exist

flowcell_df %>% mutate_at(vars(one_of("library")), as.factor) %>% summary()
flowcell_df %>% subset(!is.na(sample_id_demul)) %>% get_dupes(sample_id_demul)


## assign project_name 
flowcell_df_fordb <- flowcell_df %>% 
  left_join(., shipments_df[, c("rfid", "u01")], by = "rfid") %>%   # for the animals for which we have shipment info for 
  mutate(
    project_name = case_when(
      grepl("umich", library, ignore.case = T) ~ "u01_huda_akil",
      grepl("p\\.cal", sample_id_demul) ~ "pcal_brian_trainor",
      grepl("Plate", sample_id_demul) ~ "r01_su_guo",
      grepl("Olivier_Oxy", u01) ~ "u01_olivier_george_oxycodone",
      grepl("Olivier_Co", u01) ~ "u01_olivier_george_cocaine",
      grepl("Mitchell", u01) ~ "u01_suzanne_mitchell",
      grepl("Jhou", u01) ~ "u01_tom_jhou")
    ) # for the animals for which we don't have shipment info for 
  # select(-one_of("u01")) %>% 
  # rename("rfid" = "sample_id_demul") 
  




## upload the pgdump file into the db

con <- dbConnect(dbDriver("PostgreSQL"), dbname="PalmerLab_Datasets",user="postgres",password="postgres")
dbWriteTable(con, c("sample_tracking","sample_barcode_library"), value = flowcell_df_fordb, row.names = FALSE)

dbExecute(con,"ALTER TABLE sample_tracking.sample_barcode_library RENAME COLUMN \"sample_id_demul\" TO \"rfid\"")
dbExecute(con,"ALTER TABLE sample_tracking.sample_barcode_library ADD PRIMARY KEY(rfid,project_name)")
  
dbExecute(con, "sp_columns sample_tracking.sample_barcode_library")
dbExecute(con, "SELECT COLUMN_NAME FROM sample_tracking.sample_barcode_library")


## use dbSendQuery and dbFetch to see results
# example
# see column names
# dbSendQuery(con, "SELECT column_name FROM information_schema.columns where table_schema = 'sample_tracking' and table_name = 'sample_barcode_library'") %>% dbFetch

# use this to fix close resultSet before continuing error msg 
## dbClearResult(dbListResults(con)[[1]]) 

## create the sample sheet for Riyan
# setwd("~/Dropbox (Palmer Lab)/Palmer Lab/Bonnie Lin/U01/20190829_WFU_U01_ShippingMaster/Tissues/Processed")
# 
# flow_cell_original_riyan <- u01.importxlsx("2020-01-16-Flowcell Sample-Barcode list-Riptide-UMich2-Riptide03_NovaSeq01 (copy for Riyan).xlsx") # 1 table
# dataframe = list()
# for(i in 1:10){
#   dataframe[[i]] <- flow_cell_original_riyan$Sheet1 %>% group_by(Barcode) %>% slice(i)
# }
# write.xlsx(dataframe, file='Flowcell_Sample_Sheet.xlsx')











## rewrite this using rdrop2 
install.packages("httpuv")
install.packages('rdrop2')
library(rdrop2)
token <- drop_auth()
saveRDS(token, file = "token.rds") #save the tokens for local/remote use; Then in any drop_* function, pass `dtoken = token


drop_search(query = "Flowcell", path = "https://www.dropbox.com/work/Palmer%20Lab/Khai-Minh%20Nguyen/Sequencing%20Submission%20Files")







#### SENT TO SEQUENCING CORE
## 06/09/2020
## XX fix project names before uploading the sheets in the database



extractions_flowcell <- extractions_khai_df %>% 
  subset(`sampleid_barcode` %in% flow_cell_original_rip$`Sample ID`) # 288

## create this table for rsm
text(barplot(table(extractions_flowcell$u01), beside = T), 0, table(extractions_flowcell$u01))
table(extractions_flowcell$u01, extractions_flowcell$userid)

# using origin will get you the wrong cohorts?

extractions_flowcell$u01 %>% table() 
extractions_flowcell$u01_rfid_verified %>% table() 

# extractions_flowcell$origin %>% table()

olivier_spleen_list_df %>% subset(rfid %in% extractions_flowcell[which(extractions_flowcell$comments == "mismatch"),]$transponder)
extractions_flowcell[which(extractions_flowcell$comments == "mismatch"),]
extractions_flowcell %>% subset(comments == "mismatch")
# searching for duplicate entries in the sampleid barcode column FALSE FOR BOTH extractions_flowcell %>% select(transponder AND sampleid_barcode) %>% duplicated() %>% any() 
agrep("933000120117342", extractions_flowcell$transponder, value = T)
"933000120138331"
"933000120138561"

