## SAMPLE BARCODE LIBRARY 
# TABLE GENERATED BY KHAI/HANNAH 
# INFO IN THIS TABLE IS USED FOR DEMULTIPLEXING 

# columns should include RFID, project_name, barcode, library, and notes 


################################# 
## SAMPLE BARCODE LIBRARY TABLE 
################################# 

# get rid of the Riptide filter to see the UMich data
# setwd("~/Dropbox (Palmer Lab)/Palmer Lab/Bonnie Lin/U01/20190829_WFU_U01_ShippingMaster/Tissues/Original")
setwd("~/Dropbox (Palmer Lab)/Palmer Lab/Khai-Minh Nguyen/Sequencing Submission Files")
flowcell_files <- list.files(path = ".", pattern = "^\\d{4}-\\d{2}-\\d{2}-Flowcell Sample-Barcode list.*[^)].xlsx")

u01.importxlsx <- function(xlname){
  path_sheetnames <- readxl::excel_sheets(xlname)
  df <- lapply(readxl::excel_sheets(path = xlname), readxl::read_excel, path = xlname)
  names(df) <- path_sheetnames
  return(df)
} 

flowcell <- lapply(flowcell_files, function(x){
  x <- u01.importxlsx(x)[[1]] %>% 
    clean_names() 
  return(x)
})
names(flowcell) <- flowcell_files 

flowcell_df <- flowcell %>% rbindlist(idcol = "filename", fill = T, use.names = T) %>% 
  mutate(comment = coalesce(comments_8, comments_9)) %>% 
  select(-c("x7", "comments_8", "comments_9", "flow_cell_lane")) %>%  # columns that only contain NA or have been coalesced
  # dplyr::filter(grepl("Riptide", library)) %>% 
  mutate(comment = toupper(comment)) %>% 
  mutate(rfid = ifelse(grepl("^\\d{9}$", sample_id), paste0("933000", sample_id),
                       ifelse(grepl("\\d{15}", sample_id), sample_id, sample_id_demul)))  # create a column for rfid if it doesn't already exist

flowcell_df %>% mutate_at(vars(one_of("library")), as.factor) %>% summary()
flowcell_df %>% subset(!is.na(sample_id_demul)) %>% get_dupes(sample_id_demul)

# check for dupes
flowcell_df %>% get_dupes(rfid)

# fix dupes and wrong rfid
flowcell_df <- flowcell_df %>%
  select(-comments) %>% 
  mutate(flag = "NA") %>% 
  mutate(comment = ifelse(rfid == "933000120138361"&library=="Riptide-01", "dupe ID fixed 07/23/2020", comment), 
    rfid = replace(rfid, rfid == "933000120138361"&library=="Riptide-01", "933000120138561"),
    
    comment = ifelse(rfid == "933000120157342"&library=="Riptide-01", "Original RFID was 933000120157342", comment),
    rfid = replace(rfid, rfid == "933000120157342"&library=="Riptide-01", "933000120117342"),
    flag = replace(flag, rfid == "933000120117342", "Suspect RFID"), 
    
    comment = ifelse(rfid == "933000320046825"&library=="Riptide-06", "Original RFID was 933000320046825", comment),
    rfid = replace(rfid, rfid == "933000320046825"&library=="Riptide-06", "933000320045825"),
    flag = replace(flag, rfid == "933000320045825", "Suspect RFID"), 
    
    comment = ifelse(rfid == "933000520138331"&library=="Riptide-01", "Original RFID was 933000520138331", comment),
    rfid = replace(rfid, rfid == "933000520138331"&library=="Riptide-01", "933000120138331"),
    flag = replace(flag, rfid == "933000120138331", "Suspect RFID"))

# post fix check for dupes 
flowcell_df %>% get_dupes(rfid)

## assign project_name and fix library contents
flowcell_df_fordb <- flowcell_df %>% 
  left_join(., shipments_df[, c("rfid", "u01")], by = "rfid") %>%   # for the animals for which we have shipment info for 
  mutate(
    project_name = case_when(
      grepl("umich", library, ignore.case = T) ~ "u01_huda_akil",
      grepl("p\\.cal", sample_id_demul) ~ "pcal_brian_trainor",
      grepl("Plate", sample_id_demul) ~ "r01_su_guo",
      grepl("Olivier_Oxy", u01) ~ "u01_olivier_george_oxycodone",
      grepl("Olivier_Co", u01) ~ "u01_olivier_george_cocaine",
      grepl("Mitchell", u01) ~ "u01_suzanne_mitchell",
      grepl("Jhou", u01) ~ "u01_tom_jhou",
      grepl("Kalivas$", u01) ~ "u01_peter_kalivas_us",
      grepl("Kalivas_Italy", u01) ~ "u01_peter_kalivas_italy")
    ) %>%  # for the animals for which we don't have shipment info for 
  mutate(rfid = coalesce(rfid, sample_id)) %>% 
  rowwise() %>% 
  mutate(library = gsub("-", "", library),
         library = replace(library, grepl("UMich", library), gsub("(\\d)", "0\\1", library))) %>% 
  mutate(rfid = replace(rfid, grepl("Plate", rfid), paste0(gsub("_", "-", rfid))),
         rfid = replace(rfid, grepl("Plate", rfid), paste0(gsub("-(\\D)(\\d)$", "-\\2\\1", rfid))),
         project_name = replace(project_name, grepl("Plate", rfid), "r01_su_guo")) %>% # fix the plate names for zebrafish
  ungroup()  
  
## CREATE SAMPLE BARCODE LIBRARY TABLE
sample_barcode_lib <- flowcell_df_fordb %>% 
  rename("comments" = "comment",
         "library_name" = "library") %>% 
  select(rfid, project_name, barcode, library_name, pcr_barcode, filename, comments, flag)

## XX flowcell_df_fordb %>% mutate(project_name = replace(project_name, grepl("Plate", rfid), "r01_su_guo"), project_name = replace(project_name, grepl("^000|7", rfid)&is.na(project_name), "riptide_control"), project_name = replace(project_name, grepl("Kalivas", u01), "u01_peter_kalivas_us")) %>% select(filename, project_name) %>% table(exclude = NULL) 
## PICK UP HERE -- 09/22/2020




## upload the pgdump file into the db

con <- dbConnect(dbDriver("PostgreSQL"), dbname="PalmerLab_Datasets",user="postgres",password="postgres")
dbWriteTable(con, c("sample_tracking","sample_barcode_library"), value = flowcell_df_fordb, row.names = FALSE)

dbExecute(con,"ALTER TABLE sample_tracking.sample_barcode_library RENAME COLUMN \"sample_id_demul\" TO \"rfid\"")
dbExecute(con,"ALTER TABLE sample_tracking.sample_barcode_library ADD PRIMARY KEY(rfid,project_name)")
  
dbExecute(con, "sp_columns sample_tracking.sample_barcode_library")
dbExecute(con, "SELECT COLUMN_NAME FROM sample_tracking.sample_barcode_library")


## use dbSendQuery and dbFetch to see results
# example
# see column names
# dbSendQuery(con, "SELECT column_name FROM information_schema.columns where table_schema = 'sample_tracking' and table_name = 'sample_barcode_library'") %>% dbFetch

# use this to fix close resultSet before continuing error msg 
## dbClearResult(dbListResults(con)[[1]]) 

## create the sample sheet for Riyan
# setwd("~/Dropbox (Palmer Lab)/Palmer Lab/Bonnie Lin/U01/20190829_WFU_U01_ShippingMaster/Tissues/Processed")
# 
# flow_cell_original_riyan <- u01.importxlsx("2020-01-16-Flowcell Sample-Barcode list-Riptide-UMich2-Riptide03_NovaSeq01 (copy for Riyan).xlsx") # 1 table
# dataframe = list()
# for(i in 1:10){
#   dataframe[[i]] <- flow_cell_original_riyan$Sheet1 %>% group_by(Barcode) %>% slice(i)
# }
# write.xlsx(dataframe, file='Flowcell_Sample_Sheet.xlsx')

## Sending data to Graham 07/22/2020
setwd("~/Dropbox (Palmer Lab)/Palmer Lab/Bonnie Lin/U01/20190829_WFU_U01_ShippingMaster/Tissues/Processed")
genotype <- list()
genotype[[1]] <- read.csv("2020-01-16-Flowcell Sample-Barcode list-Riptide-UMich2-Riptide03_NovaSeq01 (copy for Riyan).csv") %>% clean_names %>% mutate_all(as.character)
genotype[[2]] <- read.csv("SampleSheet.csv") %>% clean_names %>% mutate_all(as.character) %>% rename("barcode" = "sample_barcode", "library" = "library_id")

genotype_df <- genotype %>% rbindlist(fill = T)
# for hs rats, riyan is using [sample_id]-[sample_name] as the unique combination
genotype_df <- genotype_df %>% mutate(genotype_id = paste0(sample_id, "-", sample_name),
                                      genotype_id = gsub(" ", "", genotype_id))





## rewrite this using rdrop2 
install.packages("httpuv")
install.packages('rdrop2')
library(rdrop2)
token <- drop_auth()
saveRDS(token, file = "token.rds") #save the tokens for local/remote use; Then in any drop_* function, pass `dtoken = token


drop_search(query = "Flowcell", path = "https://www.dropbox.com/work/Palmer%20Lab/Khai-Minh%20Nguyen/Sequencing%20Submission%20Files")







